In [153]:
from scipy.optimize import fsolve,leastsq
import numpy as np

In [154]:
# Temporal Difference Learning

In [219]:
class TD_lambda:
    def __init__(self, probToState,valueEstimates,rewards):
        self.probToState = probToState
        self.valueEstimates = valueEstimates
        self.rewards = rewards
        self.td1 = self.get_vs0(1)
    def get_vs0(self,lambda_):
        probToState = self.probToState
        valueEstimates = self.valueEstimates
        rewards = self.rewards
        vs = dict(zip(['vs0','vs1','vs2','vs3','vs4','vs5','vs6'],list(valueEstimates)))

        vs5 = vs['vs5'] + 1*(rewards[6]+1*vs['vs6']-vs['vs5'])
        vs4 = vs['vs4'] + 1*(rewards[5]+lambda_*rewards[6]+lambda_*vs['vs6']+(1-lambda_)*vs['vs5']-vs['vs4'])
        vs3 = vs['vs3'] + 1*(rewards[4]+lambda_*rewards[5]+lambda_**2*rewards[6]+lambda_**2*vs['vs6']+lambda_*(1-lambda_)*vs['vs5']+(1-lambda_)*vs['vs4']-vs['vs3'])
        vs1 = vs['vs1'] + 1*(rewards[2]+lambda_*rewards[4]+lambda_**2*rewards[5]+lambda_**3*rewards[6]+lambda_**3*vs['vs6']+lambda_**2*(1-lambda_)*vs['vs5']+lambda_*(1-lambda_)*vs['vs4']+\
                             (1-lambda_)*vs['vs3']-vs['vs1'])
        vs2 = vs['vs2'] + 1*(rewards[3]+lambda_*rewards[4]+lambda_**2*rewards[5]+lambda_**3*rewards[6]+lambda_**3*vs['vs6']+lambda_**2*(1-lambda_)*vs['vs5']+lambda_*(1-lambda_)*vs['vs4']+\
                             (1-lambda_)*vs['vs3']-vs['vs2'])
        vs0 = vs['vs0'] + probToState*(rewards[0]+lambda_*rewards[2]+lambda_**2*rewards[4]+lambda_**3*rewards[5]+lambda_**4*rewards[6]+lambda_**4*vs['vs6']+lambda_**3*(1-lambda_)*vs['vs5']+\
                                       +lambda_**2*(1-lambda_)*vs['vs4']+lambda_*(1-lambda_)*vs['vs3']+(1-lambda_)*vs['vs1']-vs['vs0']) +\
                (1-probToState)*(rewards[1]+lambda_*rewards[3]+lambda_**2*rewards[4]+lambda_**3*rewards[5]+lambda_**4*rewards[6]+lambda_**4*vs['vs6']+lambda_**3*(1-lambda_)*vs['vs5']+\
                                       +lambda_**2*(1-lambda_)*vs['vs4']+lambda_*(1-lambda_)*vs['vs3']+(1-lambda_)*vs['vs2']-vs['vs0'])
        return vs0
    def get_lambda(self,x0=np.linspace(0.1,1,10)):
        return fsolve(lambda lambda_:self.get_vs0(lambda_)-self.td1, x0)

In [220]:
# 1

In [221]:
probToState=0.12
valueEstimates=[0.0,4.1,10.9,0.0,10.1,0.0,0.0]
rewards=[0.0,5.3,3.6,4.0,-1.2,0.4,5.3]

In [222]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([0.45398786, 0.45398786, 0.45398786, 0.45398786, 0.45398786,
       0.45398786, 0.45398786, 1.        , 1.        , 1.        ])

In [223]:
# 2

In [224]:
probToState=0.34
valueEstimates=[0.0,23.1,0.0,3.6,8.5,20.1,0.0]
rewards=[-4.9,5.8,-4.3,2.0,8.9,-1.8,3.5]

In [225]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([-0.35584711, -0.35584711,  0.63759781,  0.63759781,  0.63759781,
        0.63759781,  0.63759781,  0.63759781,  1.        ,  1.        ])

In [226]:
# 3

In [227]:
probToState=0.64
valueEstimates=[0.0,0.0,9.3,0.0,21.8,5.0,11.5]
rewards=[-4.0,-2.2,3.8,6.5,-2.8,-4.1,7.4]

In [228]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([ 1.        , -0.61946694,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [229]:
# 4 

In [230]:
probToState=0.8
valueEstimates=[0.0,14.7,-2.4,14.7,20.7,16.7,0.0]
rewards=[-1.1,-1.6,6.1,-1.7,3.7,-1.5,9.5]

In [231]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([0.46985002, 0.46985002, 0.46985002, 0.46985002, 0.46985002,
       0.46985002, 0.46985002, 0.46985002, 1.        , 1.        ])

In [232]:
# 5

In [233]:
probToState=0.72
valueEstimates=[0.0,0.0,23.7,17.1,22.9,7.4,0.0]
rewards=[7.0,8.5,9.9,1.6,8.4,-0.7,-2.3]

In [234]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([0.30786869, 0.30786869, 0.30786869, 0.30786869, 0.30786869,
       0.30786869, 0.30786869, 1.        , 1.        , 1.        ])

In [235]:
# 6

In [255]:
probToState=1.0
valueEstimates=[0.0,0.0,2.1,0.0,21.3,7.5,-0.3]
rewards=[-4.5,-0.5,4.0,1.4,6.3,0.0,-2.2]

In [256]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([ 0.58137117,  0.58137117,  0.58137117,  0.58137117,  0.58137117,
        0.58137117,  0.58137117, -0.55831148,  1.        ,  1.        ])

In [238]:
# 7

In [239]:
probToState=0.79
valueEstimates=[0.0,1.1,1.5,0.0,0.0,14.9,15.5]
rewards=[9.7,-1.7,5.3,2.0,-0.5,0.4,0.0]

In [240]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [241]:
# 8

In [242]:
probToState=0.16
valueEstimates=[0.0,0.0,0.0,-0.2,15.3,16.4,16.6]
rewards=[3.2,0.0,6.9,3.8,-3.4,2.2,0.9]

In [243]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([-1.6871357,  1.       ,  1.       ,  1.       ,  1.       ,
        1.       ,  1.       ,  1.       ,  1.       ,  1.       ])

In [244]:
# 9

In [245]:
probToState=0.66
valueEstimates=[0.0,1.7,14.3,0.0,20.7,8.9,22.0]
rewards=[2.4,-3.0,1.9,0.0,7.2,-4.6,0.4]

In [246]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([ 1.        ,  1.        , -0.62985143,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [248]:
# 10

In [249]:
probToState=0.4
valueEstimates=[0.0,0.0,2.1,13.9,8.2,0.0,7.4]
rewards=[-4.4,-3.3,1.7,0.5,0.0,2.1,4.3]

In [250]:
TD = TD_lambda(probToState,valueEstimates,rewards)
TD.get_lambda()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])